### ISSUE TITLE
Issues with Script - Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by clovisd** [nevma/wordpress-staging#1]
Hey there!

I'm trying to set this script up on a server for staging a wordpress site. However I've run into one big issue, even as root the script can't access the database / talk to SQL and as such isn't really able to do anything. Is there any way to get around this or set the password in the config somewhere?

I'm assuming this is setup for systems with no default mysql passwords being set?

Thank you,
C

**Comment by nevma** [comment]
Hello, there, 

I will be happy to help! Can you tell me where exactly you have spotted the fact that even root cannot access the database? Is it some error that our code has produced or some log? 

However, it usually depends on your server setup to make sure that users like the root have access to the database, which is a very common scenario! 

Cheers,
Takis

**Comment by clovisd** [comment]
Hello! I guess I misphrased that, I should have said that even as root, mysql commands and access requires a password on my install. 

As such, I was wondering if and how I could specify the root user database password.
Thanks!

**Comment by nevma** [comment]
Hello, again, 

I see what you mean, but, unfortunately, we have made the assumption that root has full access to the MySQL binaries and the everything inside the MySQL installation. Right now your only option is to fix your setup so that root has unconditional access to MySQL. Sorry about that! 

Cheers, 
Takis

**Comment by clovisd** [comment]
That's just bad security.

**Comment by nevma** [comment]
Mmm, no it's not really! We are talking about the root user here. The user who already has access to everything in a Linux installation. And we like to take advantage of this convenience because this tool is designed for very specific purposes and setups.

**Comment by clovisd** [comment]
Isn't setting a application password for the root user the first thing MySQL prompts for during installation on most Linux installs? My root user and mysql root user share the same username "root" and password, I just can't access mysql or run mysql commands (using `sudo` or as `root` user) without including or being prompted for a password.

I would argue that putting a password on your mysql instance, regardless of the setup and usage, additional security is always better. It's not extremely complicated to pass a password in scripts via command line.

Anyhow, thanks for your insight and replies, sorry to have wasted your time.

**Comment by nevma** [comment]
The environment to which this tool was targeted at is a WHM/CPanel installation, which is one of the most common setups in the hosting world today. However, this environment is lacking a staging utility for WordPress and this is what we tried to build here. And indeed we tried to do it as simply and efficiently as possible. 

In this environment MySQL is not accessible to outside users and IPs by default, at least not unless it is specifically  configured to do otherwise. So, in such a setup, one's MySQL instance is as secure as the root user. But this is as good as it gets in a Linux machine anyway. And it is good enough! 

We realise that this whole setup is a bit simplistic, but, given the circumstances, it is still secure and quite useful. This was done by design, in order to have a quick and useful tool, not a product. There are dozens of little things that could be enhanced towards this direction. 

We do appreciate your comments and effort trying it out!
